### ISSUE TITLE
Not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by bourgouinadrien** [huntergregal/mimipenguin#19] opened 2017-04-14 07:28 UTC
> 09:18 abourgouin@Atuin ~/dev/mimipenguin(master) $ cat /proc/version
> Linux version 4.4.0-72-generic (buildd@lcy01-24) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #93~14.04.1-Ubuntu SMP Fri Mar 31 15:05:15 UTC 2017

Here the result of running command : 
https://pastebin.com/9MG3Ur4L

**Comment by huntergregal** [comment] 2017-04-14 16:04
Woah, first time I've seen quotes in the salt of the your hash!

Nice find - I'll make a quick fix for this soon. Just need to escape the quotes in the salt before passing it into the hashing function. Thanks for bringing up this issue.

**Comment by bourgouinadrien** [comment] 2017-04-14 16:11
For shell grammar verification, you can use shellcheck
https://github.com/koalaman/shellcheck

**Comment by huntergregal** [comment] 2017-04-14 16:33
@bourgouinadrien I'm going to check that out now. Thanks for the tip. Also try it again with a fresh pull, I just pushed a fix

**Comment by bourgouinadrien** [comment] 2017-04-14 16:38
@huntergregal I'll try on Tuesday, hoping I'll remember to ;)

**Comment by huntergregal** [comment] 2017-04-14 16:56
Shellcheck is awesome. I cleaned up a lot of small grammar in my code. 

I'm going to close this issue as I am pretty confident the problem is fixed. If it still persists please do open another issue. thanks for helping make this project better!

**Closed by huntergregal** 2017-04-14 16:56 UTC

**Comment by bourgouinadrien** [comment] 2017-04-20 13:42
So, I forgot to test again before 5 minutes ago...
Just to say it works fine now ;)
